sudo: required  # Required for docker
services:
  - docker

install:
  - npm install -g dockerlint
  - docker pull ${DOCKER_REPOSITORY}:last_successful_build || true
  - docker pull ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} || true
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .

script:


after_success:
    # TODO: Add docker push